apiVersion: v1
kind: Service
metadata:
  name: geo-lead-distribution-service
  labels:
    app: geo-lead-distribution
spec:
  type: LoadBalancer
  selector:
    app: geo-lead-distribution
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
